version: "3"
services:
  app:
    build: .
    container_name: guess
    volumes:
    - ./:/home/guess
    ports:
    - "8030:8080"

  mysql:
    image: mysql:8.0
    container_name: mysql
    volumes:
    - db_data:/var/lib/mysql
    restart: always
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: guess
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123123

volumes:
  db_data: {}
